version: '3.8'

services:
  backend:
    build:
      context: ./backend
    image: fastfood:latest
    ports:
      - "4000:4000"
    restart: unless-stopped
    networks:
      - my_network

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./Frontend/build:/var/www/build  
      - ./Frontend/nginx.conf:/etc/nginx/conf.d/default.conf  
    restart: always
    networks:
      - my_network

  

networks:
  my_network:
    driver: bridge
